name: .NET

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching release/v*, i.e. release/v1.0, release/v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    # Prepare .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    # Build project (Windows)
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish (Windows)
      run: dotnet publish --configuration Release --output build/Release/Windows --self-contained false --runtime win-x64
    - name: Publish (Linux)
      run: dotnet publish --configuration Release --output build/Release/Linux --self-contained false --runtime linux-x64

    # Create zip from artifacts
    - name: Package
      run: |
        zip -r build/vuserver-win64.zip build/Release/Windows
        zip -r build/vuserver-linux64.zip build/Release/Linux

    # Create github release and publish artifacts
    - uses: "marvinpinto/action-automatic-releases@v1.1.0"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: Release ${{ github.ref }}
        files: |
          README.md
          build/vuserver-win64.zip
          build/vuserver-linux64.zip